// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/api/api.proto

package pdfcomposer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pdf struct {
	File                 []byte   `protobuf:"bytes,1,opt,name=File,proto3" json:"File,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pdf) Reset()         { *m = Pdf{} }
func (m *Pdf) String() string { return proto.CompactTextString(m) }
func (*Pdf) ProtoMessage()    {}
func (*Pdf) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ffe71976e461794, []int{0}
}

func (m *Pdf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pdf.Unmarshal(m, b)
}
func (m *Pdf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pdf.Marshal(b, m, deterministic)
}
func (m *Pdf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pdf.Merge(m, src)
}
func (m *Pdf) XXX_Size() int {
	return xxx_messageInfo_Pdf.Size(m)
}
func (m *Pdf) XXX_DiscardUnknown() {
	xxx_messageInfo_Pdf.DiscardUnknown(m)
}

var xxx_messageInfo_Pdf proto.InternalMessageInfo

func (m *Pdf) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type Images struct {
	Image                []byte   `protobuf:"bytes,1,opt,name=Image,proto3" json:"Image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Images) Reset()         { *m = Images{} }
func (m *Images) String() string { return proto.CompactTextString(m) }
func (*Images) ProtoMessage()    {}
func (*Images) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ffe71976e461794, []int{1}
}

func (m *Images) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Images.Unmarshal(m, b)
}
func (m *Images) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Images.Marshal(b, m, deterministic)
}
func (m *Images) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Images.Merge(m, src)
}
func (m *Images) XXX_Size() int {
	return xxx_messageInfo_Images.Size(m)
}
func (m *Images) XXX_DiscardUnknown() {
	xxx_messageInfo_Images.DiscardUnknown(m)
}

var xxx_messageInfo_Images proto.InternalMessageInfo

func (m *Images) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func init() {
	proto.RegisterType((*Pdf)(nil), "pdfcompose.Pdf")
	proto.RegisterType((*Images)(nil), "pdfcompose.Images")
}

func init() { proto.RegisterFile("server/api/api.proto", fileDescriptor_9ffe71976e461794) }

var fileDescriptor_9ffe71976e461794 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x4e, 0x2d, 0x2a,
	0x4b, 0x2d, 0xd2, 0x4f, 0x2c, 0xc8, 0x04, 0x61, 0xbd, 0x82, 0xa2, 0xfc, 0x92, 0x7c, 0x21, 0xae,
	0x82, 0x94, 0xb4, 0xe4, 0xfc, 0xdc, 0x82, 0xfc, 0xe2, 0x54, 0x25, 0x49, 0x2e, 0xe6, 0x80, 0x94,
	0x34, 0x21, 0x21, 0x2e, 0x16, 0xb7, 0xcc, 0x9c, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x9e, 0x20,
	0x30, 0x5b, 0x49, 0x8e, 0x8b, 0xcd, 0x33, 0x37, 0x31, 0x3d, 0xb5, 0x58, 0x48, 0x84, 0x8b, 0x15,
	0xcc, 0x82, 0x4a, 0x43, 0x38, 0x46, 0x1e, 0x5c, 0x82, 0x01, 0x29, 0x69, 0xce, 0x10, 0x83, 0x82,
	0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x8c, 0xb9, 0x38, 0x82, 0x53, 0xf3, 0x52, 0x40, 0x06,
	0x08, 0x09, 0xe9, 0x21, 0x2c, 0xd2, 0x83, 0x18, 0x25, 0xc5, 0x8f, 0x2c, 0x16, 0x90, 0x92, 0xa6,
	0xc4, 0xa0, 0xc1, 0xe8, 0x24, 0x18, 0xc5, 0x5f, 0x90, 0x9d, 0xae, 0x8f, 0x90, 0x29, 0x4a, 0x62,
	0x03, 0x3b, 0xd5, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x71, 0x8e, 0x6e, 0xc2, 0x00, 0x00,
	0x00,
}
